
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.Entry entry1;

	private global::Gtk.Label Dato;

	private global::Gtk.Button btnAceptar;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entry1 = new global::Gtk.Entry();
		this.entry1.CanFocus = true;
		this.entry1.Name = "entry1";
		this.entry1.IsEditable = true;
		this.entry1.InvisibleChar = '●';
		this.fixed1.Add(this.entry1);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.entry1]));
		w1.X = 107;
		w1.Y = 72;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Dato = new global::Gtk.Label();
		this.Dato.Name = "Dato";
		this.Dato.LabelProp = global::Mono.Unix.Catalog.GetString("Mensaje");
		this.fixed1.Add(this.Dato);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.Dato]));
		w2.X = 165;
		w2.Y = 172;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnAceptar = new global::Gtk.Button();
		this.btnAceptar.CanFocus = true;
		this.btnAceptar.Name = "btnAceptar";
		this.btnAceptar.UseUnderline = true;
		this.btnAceptar.Label = global::Mono.Unix.Catalog.GetString("OK");
		this.fixed1.Add(this.btnAceptar);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnAceptar]));
		w3.X = 170;
		w3.Y = 118;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
